### ISSUE TITLE
ipyleaflet.DrawControl() does not respond to polygon deletion; FullScreenControl has no effect.

### ISSUE THREAD

**Issue by mortcanty** [googlecolab/colab-cdn-widget-manager#10]
Hi again, 

 I found a couple of bugs in DrawControl(). The snippet below I hope reproduces the problem when run on Colab. The draw handler prints 'created' after polygon/line segment completion, but is not triggered upon polygon/line segment deletion. It works properly, printing 'deleted', for circle marker.  The full screen control does not appear to be working at all.

import ipywidgets
from ipyleaflet import (Map,DrawControl,
                        basemaps,basemap_to_tiles,
                        LayersControl,
                        FullScreenControl)

osm = basemap_to_tiles(basemaps.OpenStreetMap.Mapnik)

def handle_draw(self, action, geo_json):
    print(action)

dc = DrawControl()    
dc.on_draw(handle_draw)

lc = LayersControl(position='topright')
fs = FullScreenControl(position='topleft')    

m = Map(center=[51.0,6.4], 
          zoom=11, 
          layout={'height':'400px','width':'600px'},
          layers=(osm,),
          controls=(dc,lc,fs))

from IPython.display import display, Javascript
display(Javascript('''
google.colab.widgets.installCustomManager('https://ssl.gstatic.com/colaboratory-static/widgets/colab-cdn-widget-manager/158219452c5c5bf9/manager.min.js');
'''))
m

**Comment by blois** [comment]
Thanks! I'll have to dig into the draw tool & deletion. 

Currently fullscreen is not available within the sandboxed iframe for security concerns but from the cell toolbar (at the top-right of the cell) you can choose 'View output fullscreen' (or ctrl-shift-p View output fullscreen) to have the output go full screen. The concern is around spoofing attacks from code running within the iframe.

**Comment by mortcanty** [comment]
I don't know if this is the same issue, but ipyleaflet.Map() no longer displays at all, e.g., running  the above snippet.

**Comment by blois** [comment]
See https://github.com/googlecolab/colabtools/issues/498#issuecomment-916996133

```python
!pip install -q ipyleaflet

from google.colab import output
output.enable_custom_widget_manager()
```

Then the custom widgets will be enabled for all later cells.

The fix for this issue will be rolling out in a day or two, in the meantime the above stanza can be changed to manually pick up the version:

```python
from google.colab.output import _widgets
_widgets._install_custom_widget_manager('https://ssl.gstatic.com/colaboratory-static/widgets/colab-cdn-widget-manager/bf763107cca07459/manager.min.js')
```

**Comment by mortcanty** [comment]
Thank you!

**Comment by blois** [comment]
This fix should be live.
