### ISSUE TITLE
Plotly widgets do not work

### ISSUE THREAD

**Issue by blois** [googlecolab/colab-cdn-widget-manager#19]
From https://github.com/googlecolab/colabtools/issues/498#issuecomment-975863250

```python
from google.colab.output import _widgets
_widgets._install_custom_widget_manager('http://127.0.0.1:9897/manager.dev.js')

import plotly.graph_objects as go
f = go.FigureWidget(layout={'height': 400, 'width': 400})
display(f)
```

The issue is that the current version (1.4.0) targets Phosphor and relies on `processPhosphorMessage` being called: 
https://github.com/plotly/plotly.py/blob/df19fc702b309586cc24e25373b87e8bdbb3ff60/packages/javascript/jupyterlab-plotly/src/Figure.ts#L907

This package currently targets widgets 5.0.0 which has not yet had a stable release. In 5.0 Phosphor was renamed to Lumino and all related methods were renamed as well. See https://github.com/jupyter-widgets/ipywidgets/commit/a558dacfe31cd78e63579dddec5ed8c0ca59dc36.

 - processMessage is called here: https://github.com/googlecolab/colab-cdn-widget-manager/blob/6af7a6ef408e6c6d07ea89af03e7abd3c640c63a/src/manager.ts#L192
 - Which calls processLuminoMessage: https://github.com/jupyter-widgets/ipywidgets/blob/4160af3f0f86885ad56b66fe6ddbc85bb2e7a255/packages/base/src/widget.ts#L824

This is similar to https://github.com/googlecolab/colab-cdn-widget-manager/issues/12.

**Comment by blois** [comment]
The fix for this should now be in production.

The result of the notebook in https://github.com/googlecolab/colabtools/issues/498#issuecomment-971983665-
![image](https://user-images.githubusercontent.com/2152569/143303493-f2ac3a26-db66-4b01-a43d-904d1c649a9f.png)

**Comment by cardinalgeo** [comment]
> The fix for this should now be in production.
> 
> The result of the notebook in [googlecolab/colabtools#498 (comment)](https://github.com/googlecolab/colabtools/issues/498#issuecomment-971983665) ![image](https://user-images.githubusercontent.com/2152569/143303493-f2ac3a26-db66-4b01-a43d-904d1c649a9f.png)

Hi @Blois, as your screenshot shows, only the static plot is produced; the widgets that control it are not (they only appear when the block is run with `g.show()` removed). 

@kylebarron dug into this a bit [here](https://github.com/googlecolab/colabtools/issues/498#issuecomment-981908357), but my inexperience has prevented me from diving further, though I'd be happy to dig deeper if you can point me in the right direction. Is the issue something that needs to be addressed on the Colab side, or does it require creating an issue in the Plotly repo?

**Comment by blois** [comment]
@cardinalgeo I think this is more of a Plotly question, possibly related to https://plotly.com/python/renderers/#setting-the-default-renderer?

Just so I understand with a simpler example, starting with:

```python
from google.colab import output
output.enable_custom_widget_manager()

import plotly.graph_objects as go

f = go.FigureWidget()
```

There are effectively two mechanisms to display:

```python
# renderer='colab' is the default in Colab, but can be tweaked.
f.show(renderer="colab")
```

and:
```python
display(f)
```

In the first, Plotly is returning a combination of HTML & JS which is rendered. But it sounds like you're looking for `.show()` to return a Widget which will be rendered? I'm not sure what mechanisms Plotly has for that.

I may be misunderstanding this though.

**Comment by kylebarron** [comment]
From my reading of Plotly's codebase, `f.show()` renders with an iframe; `display(f)` is renders the widget.

**Comment by Yuri-Nassar** [comment]
Hi guys. Any update on this?
I am trying to use the go. Sankey, but it does not show up in the colab (f.show() or display(f) shows nothing).
I use matplotlib in other methods and they work properly. 
Is it a problem of plotly to work with widgets on colab?
